export const FETCH_LANGUAGES_REQUEST = 'FETCH_LANGUAGES_REQUEST';
export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS';
export const FETCH_LANGUAGES_ERROR = 'FETCH_LANGUAGES_ERROR';

export const FETCH_RANDOM_REPOSITORY_REQUEST = 'FETCH_RANDOM_REPOSITORY_REQUEST';
export const FETCH_RANDOM_REPOSITORY_SUCCESS = 'FETCH_RANDOM_REPOSITORY_SUCCESS';
export const FETCH_RANDOM_REPOSITORY_ERROR = 'FETCH_RANDOM_REPOSITORY_ERROR';
